import { useState, useEffect } from 'react'
import './App.css'

export default function App() {
  const [scrolled, setScrolled] = useState(false);
  
  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <div className="app-container">
      <nav className={`navbar ${scrolled ? 'scrolled' : ''}`}>
        <div className="logo">ground zero</div>
        <div className="nav-links">
          <span>Home</span>
          <span>Features</span>
          <span>About</span>
          <button className="nav-btn">Get Started</button>
        </div>
      </nav>

      <main className="hero-section">
        <div className="glass-card fade-in">
          <div className="status-badge">Live System Simulation</div>
          <h1>ground zero</h1>
          <p className="description">
            build a website for a cafe named ground zero
          </p>
          <div className="hero-actions">
            <button className="primary-btn">Explore Platform</button>
            <button className="secondary-btn">View Docs</button>
          </div>
        </div>
      </main>

      <section className="features-grid">
        <div className="feature-card">
          <div className="icon">🚀</div>
          <h3>Lightning Fast</h3>
          <p>Optimized for peak performance and minimal latency using modern build tools.</p>
        </div>
        <div className="feature-card">
          <div className="icon">🛡️</div>
          <h3>Secure by Design</h3>
          <p>Enterprise-grade security built into every layer of the application stack.</p>
        </div>
        <div className="feature-card">
          <div className="icon">📊</div>
          <h3>Real-time Insights</h3>
          <p>Monitor your project growth and system health with real-time analytics.</p>
        </div>
      </section>

      <footer className="footer">
        <p>&copy; 2026 ground zero. Generated by DevOps Team Simulator.</p>
      </footer>
    </div>
  )
}
